In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
python_list = (1, 2, 3, 4, 5)
numpy_array = np.array([1, 2, 3, 4, 5])

In [4]:
numpy_array

array([1, 2, 3, 4, 5])

In [5]:
python_list

(1, 2, 3, 4, 5)

In [6]:
type(numpy_array)

numpy.ndarray

In [7]:
print("shape:", numpy_array.shape)

shape: (5,)


In [8]:
print("size:", numpy_array.size)

size: 5


In [9]:
print("Dimensions:", numpy_array.ndim)

Dimensions: 1


In [11]:
print("Data type:", numpy_array.dtype)

Data type: int64


part 2 creating numpy_array


In [14]:
# from list
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(f"addition of two numpy array {arr1 + arr2}")



addition of two numpy array [ 7  9 11 13 15]


In [15]:
# zero
zeros = np.zeros(10)
print("zeros:", zeros)

zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
zeros.ndim

1

In [18]:
zeros_2d = np.zeros((3, 4))
print("zeros 2D:\n", zeros_2d)

zeros 2D:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ones = np.ones(5)
print("ones aray", ones)
print("number of dims.", ones.ndim)

ones aray [1. 1. 1. 1. 1.]
number of dims. 1


In [22]:
ones_2d = np.ones((3, 5))
print("ones i 2D\n",ones_2d)

ones i 2D
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
#crat numpy arays of zeros, ones, custom numpy arays in 1 and 2d 

In [25]:
zeros = np.zeros(5)
print("zeros:", zeros)

zeros: [0. 0. 0. 0. 0.]


In [32]:
ones= np.ones(9)
print("ones:", ones)
print("number of dims.", ones.ndim)

ones: [1. 1. 1. 1. 1. 1. 1. 1. 1.]
number of dims. 1


In [33]:
ones = np.ones((2, 5))
print("ones 2d:\n", ones)
print("number of dims.", ones.ndim)

ones 2d:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
number of dims. 2


In [35]:
zeros = np.zeros((4, 6))
print("zeros 2d:\n", zeros)
print("number of dim:", zeros.ndim)

zeros 2d:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
number of dim: 2


In [49]:
Arr3 = np.array([5, 6, 7, 8, 9, 10])
Arr4 = np.array([11, 12, 13, 14, 15, 16])
print(Arr4)
print(f"addition of two numpy array {Arr3 + Arr4}")

[11 12 13 14 15 16]
addition of two numpy array [16 18 20 22 24 26]


In [50]:
Custom_2d_array = np.array([[5, 6, 7, 8, 9, 10],[11, 12, 13, 14, 15, 16],[6, 7, 8, 9, 10, 13] ])

In [51]:
print(Custom_2d_array)

[[ 5  6  7  8  9 10]
 [11 12 13 14 15 16]
 [ 6  7  8  9 10 13]]


In [52]:
print(Custom_2d_array.ndim)

2


 EXERCISE 2.1: Create the following arrays:
# 1. Array of 10 zeros
# 2. Array from 0 to 100 with step 10
# 3. 5 evenly spaced numbers between 0 and 1


In [57]:
zeros = np.zeros(10)
print("zeros:", zeros)

zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Array from 0 to 100 with stem 10
# For start (0), stop (101), step (10)
array = list(range(0, 101, 10))
print(array)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [59]:
# 5 evenly spaced numbers between 0 and 1
numbers = np.linspace(0, 1, 5)
print(numbers)

[0.   0.25 0.5  0.75 1.  ]
